import Head from "next/head";
import Image from "next/image";

import Navigation from "../components/navigation";
import Footer from "../components/footer";

export default function Details() {
  return (
    <div>
      <Head>
        <title>Ian & Theresa 2022 | August 5th, 2022 Wedding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <div className="page-bg details animate__animated animate__fadeIn">
        <div className="container text-center">
          <div className="row align-items-center">
            <div className="col-lg-12">
              <h1 className="it-title text-white text-primary ">
                Details
              </h1>
            </div>
          </div>
        </div>
      </div>

      <div className="container">
        <div className="row align-items-center">
          <div className="col-lg-6">
            <div className="it-date-box">
              <div className="it-date-label">Ceremony</div>
              <div className="it-date">Holy Spirit Catholic Church</div>
              <div className="it-location">
                1396 Lynnhaven Pkwy, Virginia Beach, VA 23453
              </div>

              <div>
                <a href="#" className="btn btn-secondary me-2 mb-2 mt-3">
                  RSVP
                </a>
              </div>
            </div>
          </div>
          <div className="col-lg-6">
            <div className="it-date-box">
              <div className="it-date-label">Reception</div>
              <div className="it-date">
                Half Moone Cruise and Celebration Center
              </div>
              <div className="it-location">
                1 Waterside Dr, Norfolk, VA 23510{" "}
              </div>

              <div>
                <a href="#" className="btn btn-secondary me-2 mb-2 mt-3">
                  RSVP
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <Footer/>
    </div>
  );
}
