import Head from "next/head";
import Image from "next/image";

import Navigation from "../components/navigation";
import Footer from "../components/footer";

export default function faqs() {
  return (
    <div>
      <Head>
        <title>FAQS | Ian & Theresa 2022 | August 5th, 2022 Wedding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <div className="page-bg registry animate__animated animate__fadeInRight mb-0">
        <div className="container text-center">
          <div className="row align-items-center">
            <div className="col-lg-12">
              <h1 className="it-title text-white text-primary ">faqs</h1>
            </div>
          </div>
        </div>
      </div>

      <div className="container">
        <div className="row align-items-center">
          <div className="col-lg-12">
            <div
              className="mt-5 text-start"
              style={{
                maxWidth: "768px",
                marginLeft: "auto",
                marginRight: "auto",
              }}
            >
              <div className="mt-5">
                <em>
                  If you have any other questions or concerns, please contact us
                  at{" "}
                  <a href="ianandtheresa2022@gmail.com">
                    ianandtheresa2022@gmail.com
                  </a>
                  .{" "}
                </em>
              </div>
              <div className="it-label">When should I RSVP?</div>
              <p>Kindly RSVP by June 30, 2022.</p>
              <div className="it-label">What is the dress code?</div>
              <p>Semi-formal or cocktail.</p>
              <div className="it-label">
                Can I bring a plus one and/or my children?
              </div>
              <p>
                Respectfully, we can only accommodate those listed on your
                invitation. Please contact us at{" "}
                <a href="mailto:ianandtheresa2022@gmail.com">
                  ianandtheresa2022@gmail.com
                </a>{" "}
                for any questions or concerns.
              </p>
              <div className="it-label">Do you have a wedding registry?</div>
              <p>
                Yes, we are registered at{" "}
                <a
                  target="_blank"
                  href="https://www.target.com/gift-registry/gift-giver?registryId=2802a9e0-ae2c-11ec-a472-b57a8cdbe910&type=WEDDING"
                >
                  Target
                </a>{" "}
                and{" "}
                <a
                  target="_blank"
                  href="https://www.amazon.com/wedding/theresa-riel-ian-fajardo-virginia-beach-august-2022/registry/2ODPG89IZIM9D
"
                >
                  Amazon
                </a>
                .
              </p>

              <div className="it-label">Where can I park?</div>
              <p>A parking lot is available at the ceremony venue. </p>
              <p>
                <strong>West Plume Street Garage</strong> 130 W Plume St,
                Norfolk, VA 23510
              </p>
              <p>
                <strong>Town Point Garage</strong> 110 W Main St, Norfolk, VA
                23510
              </p>
              <hr />
              <div className="it-date-label">covid faqs</div>
              <div className="it-label">
                How will changes be communicated before the wedding day?
              </div>
              <p>
                We are closely monitoring healthy and safety guidelines. Any
                changes will be communicated through our wedding website at
                www.ianandtheresa2022.com.{" "}
              </p>
              <div className="it-label">How many guests will be attending?</div>
              <p>
                We have invited 250+ of our closest loved ones to celebrate our
                big day.{" "}
              </p>
              <div className="it-label">
                What safety guidelines will be in place?
              </div>
              <p>
                We respectfully require that all guests ages 5 and older be
                fully vaccinated and boosted, and we plan to require proof of
                vaccination upon entrance to the reception venue. Masks will not
                be required, but we respect those that wish to wear one. Masks
                and hand sanitizer will be made available at both venues.
              </p>
              <p>
                <em>
                  We understand that the situations above may affect your
                  ability or choice to attend our wedding. This deeply saddens
                  us because we love you and will miss you, but as much as we
                  want to start our marriage with you present, we want you to
                  stay safe more. We hope that by starting this conversation
                  early, we can discuss what works best for all of us. Love, Ian
                  & Theresa
                </em>
              </p>
            </div>
          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
}
