import Head from "next/head";
import Image from "next/image";

import Navigation from "../components/navigation";
import Footer from "../components/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ian & Theresa 2022 | August 5th, 2022 Wedding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="it-jumbo-full">
        <Navigation />
        <div className="">
          <div className="row no-gutters align-items-center">
            <div className="col-lg-6 text-center  animate__animated animate__fadeIn">
              <h1 className="it-title text-primary">
                Theresa + Ian
              </h1>
              <h2 className="it-lead">are getting married!</h2>
              <div className="it-date-box">
                <div className="it-date">August 5, 2022</div>
                <div className="it-location">Virginia Beach, VA</div>
              </div>
            </div>
            <div className="col-lg-6">
              <div className="it-half-jumbo animate__animated animate__fadeIn"></div>
            </div>
          </div>
        </div>
      </div>

      <Footer style={{marginTop: "0"}}/>
    </div>
  );
}
