import Head from "next/head";
import Image from "next/image";

import Navigation from "../components/navigation";
import Footer from "../components/footer";

export default function Rsvp() {
  return (
    <div>
      <Head>
        <title>Ian & Theresa 2022 | August 5th, 2022 Wedding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <div className="animate__animated animate__fadeIn">
        <div className="container text-center">
          <div className="row align-items-center">
            <div className="col-lg-12">
              <h1 className="it-title text-primary ">
                rsvp
              </h1>
            </div>
          </div>
        </div>
      </div>

      <div className="container" style={{height: "400px"}}>
        <div className="row align-items-center">
          <div className="col-lg-12 text-center">
            <div className="it-lead">Coming soon!</div>
          </div>
        </div>
      </div>

      <Footer/>
    </div>
  );
}
