import Head from "next/head";
import Image from "next/image";

import Navigation from "../components/navigation";
import Footer from "../components/footer";

export default function Rsvp() {
  return (
    <div>
      <Head>
        <title>Ian & Theresa 2022 | August 5th, 2022 Wedding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <iframe
        style={{
          display: "block",
          width: "100%",
          height: "900px",
          border: "none",
          overflow: "visible",
        }}
        src="https://withjoy.com/ianandtheresa2022/rsvp"
      ></iframe>

      <Footer />
    </div>
  );
}
