import Head from "next/head";
import Image from "next/image";

import Navigation from "../components/navigation";
import Footer from "../components/footer";
import Star from "../components/star";

export default function ThingsToDo() {
  return (
    <div>
      <Head>
        <title>Ian & Theresa 2022 | August 5th, 2022 Wedding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <div className="page-bg thingstodo animate__animated animate__fadeIn">
        <div className="container text-center">
          <div className="row align-items-center">
            <div className="col-lg-12">
              <h1 className="it-title text-white text-primary ">
                Things to Do
              </h1>
            </div>
          </div>
        </div>
      </div>

      <div className="container">
        <div className="row">
          <div className="col-lg-6">
            <div className="todo-box">
              <div className="it-date-label">Virginia Beach</div>
              <div className="it-label">
                <Star /> Three Ships Coffee Roasters
              </div>
              <div className="it-location">
                607 19th St, Virginia Beach, VA 23451
              </div>
              <p>
                Ian’s favorite place to grab a bag of coffee beans and a cup of
                coffee. With your beverage of choice in hand, walk over to WRV,
                a local surf/skate shop, and browse their apparel.
              </p>
            </div>
            <div className="todo-box">
              <hr />
              <div className="it-label">The Atlantic</div>
              <div className="it-location">
                3004 Pacific Ave, Virginia Beach, VA 23451
              </div>
              <p>
                They have Happy Hour EVERY DAY between 3 - 6 pm that includes $1
                oysters! Located within walking distance from the beach.
              </p>
            </div>
            <div className="todo-box">
              <hr />
              <div className="it-label">New Realm Brewing</div>
              <div className="it-location">
                1209 Craft Ln, Virginia Beach, VA 23454
              </div>
              <p>
                A local restaurant/brewery that’s a short drive from the
                Oceanfront. There is plenty of indoor and outdoor space and live
                entertainment on the weekends. This is where we celebrated right
                after Ian proposed!
              </p>
            </div>
          </div>
          <div className="col-lg-6">
            <div className="todo-box">
              <div className="it-date-label">Norfolk</div>
              <div className="it-label">
                <Star />
                Alkaline
              </div>
              <div className="it-location">
                742 W 21st St, Norfolk, VA 23517
              </div>
              <p>
                Theresa&apos;s favorite ramen place! The ramen is delicious and they
                have some great filipino fusion apps too.
              </p>
            </div>
            <div className="todo-box">
              <hr />
              <div className="it-label">Grain</div>
              <div className="it-location">
                100 E Main St, Norfolk, VA 23510
              </div>
              <p>
                Norfolk&apos;s only rooftop beer garden. Right across the street from
                our wedding reception location, a great place to grab a drink
                for the afterparty!
              </p>
            </div>
            <div className="todo-box">
              <hr />
              <div className="it-label">The Veil Brewing Co.</div>
              <div className="it-location">
                2314 Colonial Ave, Norfolk, VA 23517
              </div>
              <p>
                In the Railroad District, this three-story brewery has some
                tasty beer and delicious food. Great place to grab a drink!
              </p>
            </div>
          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
}
